version: v0.6.4
allow:
  - docs.search
  - vector.search
  - tools.search_docs
  - tools.summarize
  - tools.run_command
  - tools.check_file
  - tools.read_file
  - tools.list_directory
  - tools.run_eval
  - tools.check_gates
  - tools.ensure_on_feature_branch
  - tools.safe_commit
  - tools.create_pr
  - tools.branch_diff_summary
