name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Unit tests
      run: |
        export EMBED_BACKEND=stub
        python - <<'PY'
        import os, sys, subprocess
        os.environ["EMBED_BACKEND"] = "stub"
        rc = 0
        rc |= subprocess.call([sys.executable, "lab/tests/test_summarize.py"])
        rc |= subprocess.call([sys.executable, "lab/rag/tests/test_chunk_and_retrieve.py"])
        rc |= subprocess.call([sys.executable, "lab/rag/tests/test_hybrid.py"])
        rc |= subprocess.call([sys.executable, "lab/security/tests/test_redact.py"])
        rc |= subprocess.call([sys.executable, "lab/security/tests/test_guardian.py"])
        sys.exit(rc)
        PY
    
    - name: Retrieval eval (non-blocking)
      continue-on-error: true
      run: |
        export EMBED_BACKEND=stub
        python lab/eval/run_eval.py
    
    - name: Server health check
      run: |
        chmod +x lab/tests/test_server_health.sh
        ./lab/tests/test_server_health.sh